update "Product"  set image='products/7up-bottle.jpg'   where slug='7up-bottle' and image='';
update "Product"  set image='products/7up-can.jpg'   where slug='7up-can' and image='';
update "Product"  set image='products/american-hot.jpg'   where slug='american-hot' and image='';
update "Product"  set image='products/bbq-chicken-wings.jpg'   where slug='bbq-chicken-wings' and image='';
update "Product"  set image='products/bbq-chicken.jpg'   where slug='bbq-chicken' and image='';
update "Product"  set image='products/bbq-meat-combo.jpg'   where slug='bbq-meat-combo' and image='';
update "Product"  set image='products/bbq-special.jpg'   where slug='bbq-special' and image='';
update "Product"  set image='products/ben-jerrys.jpg'   where slug='ben-jerrys' and image='';
update "Product"  set image='products/cheesy-garlic-bread-pizza.jpg'   where slug='cheesy-garlic-bread-pizza' and image='';
update "Product"  set image='products/chicken-box.jpg'   where slug='chicken-box' and image='';
update "Product"  set image='products/chicken-dippers.jpg'   where slug='chicken-dippers' and image='';
update "Product"  set image='products/chicken-hot.jpg'   where slug='chicken-hot' and image='';
update "Product"  set image='products/chicken-nuggets.jpg'   where slug='chicken-nuggets' and image='';
update "Product"  set image='products/chicken-strips.jpg'   where slug='chicken-strips' and image='';
update "Product"  set image='products/chicken-wings.jpg'   where slug='chicken-wings' and image='';
update "Product"  set image='products/chinese-special.jpg'   where slug='chinese-special' and image='';
update "Product"  set image='products/chocolate-fudge-cake.jpg'   where slug='chocolate-fudge-cake' and image='';
update "Product"  set image='products/coke-bottle.jpg'   where slug='coke-bottle' and image='';
update "Product"  set image='products/coke-can.jpg'   where slug='coke-can' and image='';
update "Product"  set image='products/country-chicken.jpg'   where slug='country-chicken' and image='';
update "Product"  set image='products/curly-fries.jpg'   where slug='curly-fries' and image='';
update "Product"  set image='products/diet-coke-can.jpg'   where slug='diet-coke-can' and image='';
update "Product"  set image='products/dips.jpg'   where slug='dips' and image='';
update "Product"  set image='products/dr-pepper-can.jpg'   where slug='dr-pepper-can' and image='';
update "Product"  set image='products/fanta-can.jpg'   where slug='fanta-can' and image='';
update "Product"  set image='products/farm-chicken.jpg'   where slug='farm-chicken' and image='';
update "Product"  set image='products/farm-pizza-classic.jpg'   where slug='farm-pizza-classic' and image='';
update "Product"  set image='products/farm-pizza-special.jpg'   where slug='farm-pizza-special' and image='';
update "Product"  set image='products/garlic-bread-cheese-bacon.jpg'   where slug='garlic-bread-cheese-bacon' and image='';
update "Product"  set image='products/garlic-bread-cheese-pepperoni.jpg'   where slug='garlic-bread-cheese-pepperoni' and image='';
update "Product"  set image='products/garlic-bread-cheese.jpg'   where slug='garlic-bread-cheese' and image='';
update "Product"  set image='products/garlic-bread.jpg'   where slug='garlic-bread' and image='';
update "Product"  set image='products/haagen-dazs.jpg'   where slug='haagen-dazs' and image='';
update "Product"  set image='products/half-and-half.jpg'   where slug='half-and-half' and image='';
update "Product"  set image='products/hawaiian.jpg'   where slug='hawaiian' and image='';
update "Product"  set image='products/hot-and-spicy.jpg'   where slug='hot-and-spicy' and image='';
update "Product"  set image='products/hot-chicken-wings.jpg'   where slug='hot-chicken-wings' and image='';
update "Product"  set image='products/hot-vegetarian.jpg'   where slug='hot-vegetarian' and image='';
update "Product"  set image='products/hotter-than-hot.jpg'   where slug='hotter-than-hot' and image='';
update "Product"  set image='products/italian-chicken.jpg'   where slug='italian-chicken' and image='';
update "Product"  set image='products/italian-meat-feast.jpg'   where slug='italian-meat-feast' and image='';
update "Product"  set image='products/italian-meatball.jpg'   where slug='italian-meatball' and image='';
update "Product"  set image='products/jalapeno-poppers.jpg'   where slug='jalapeno-poppers' and image='';
update "Product"  set image='products/margherita.jpg'   where slug='margherita' and image='';
update "Product"  set image='products/meat-combo.jpg'   where slug='meat-combo' and image='';
update "Product"  set image='products/meat-feast.jpg'   where slug='meat-feast' and image='';
update "Product"  set image='products/meat-lasagne.jpg'   where slug='meat-lasagne' and image='';
update "Product"  set image='products/meat-machine.jpg'   where slug='meat-machine' and image='';
update "Product"  set image='products/mega-ball.jpg'   where slug='mega-ball' and image='';
update "Product"  set image='products/mexican-hot.jpg'   where slug='mexican-hot' and image='';
update "Product"  set image='products/milkshake.jpg'   where slug='milkshake' and image='';
update "Product"  set image='products/mozzarella-sticks.jpg'   where slug='mozzarella-sticks' and image='';
update "Product"  set image='products/onion-rings.jpg'   where slug='onion-rings' and image='';
update "Product"  set image='products/original.jpg'   where slug='original' and image='';
update "Product"  set image='products/out-of-this-world.jpg'   where slug='out-of-this-world' and image='';
update "Product"  set image='products/pepperoni-feast.jpg'   where slug='pepperoni-feast' and image='';
update "Product"  set image='products/pepperoni-lover.jpg'   where slug='pepperoni-lover' and image='';
update "Product"  set image='products/pepperoni-special.jpg'   where slug='pepperoni-special' and image='';
update "Product"  set image='products/pepsi-bottle.jpg'   where slug='pepsi-bottle' and image='';
update "Product"  set image='products/potato-skins-cheese-bacon.jpg'   where slug='potato-skins-cheese-bacon' and image='';
update "Product"  set image='products/potato-skins-cheese.jpg'   where slug='potato-skins-cheese' and image='';
update "Product"  set image='products/potato-wedges.jpg'   where slug='potato-wedges' and image='';
update "Product"  set image='products/seafood.jpg'   where slug='seafood' and image='';
update "Product"  set image='products/spaghetti-bolognese.jpg'   where slug='spaghetti-bolognese' and image='';
update "Product"  set image='products/strawberry-cheesecake.jpg'   where slug='strawberry-cheesecake' and image='';
update "Product"  set image='products/stuffed-mushroom.jpg'   where slug='stuffed-mushroom' and image='';
update "Product"  set image='products/tango-bottle.jpg'   where slug='tango-bottle' and image='';
update "Product"  set image='products/tennessee-toffee-pie.jpg'   where slug='tennessee-toffee-pie' and image='';
update "Product"  set image='products/tex-bbq.jpg'   where slug='tex-bbq' and image='';
update "Product"  set image='products/tex-mix-platter.jpg'   where slug='tex-mix-platter' and image='';
update "Product"  set image='products/the-favourite.jpg'   where slug='the-favourite' and image='';
update "Product"  set image='products/vegetarian.jpg'   where slug='vegetarian' and image='';
update "Product"  set image='products/veggie-supreme.jpg'   where slug='veggie-supreme' and image='';
update "Product"  set image='products/water.jpg'   where slug='water' and image='';
update "Deal"     set image='deals/family-meal-1.jpg'      where slug='family-meal-1';
update "Deal"     set image='deals/family-meal-3.jpg'      where slug='family-meal-3';
update "Deal"     set image='deals/meal-for-1.jpg'      where slug='meal-for-1';
update "Deal"     set image='deals/meal-for-2.jpg'      where slug='meal-for-2';
update "Deal"     set image='deals/mega-deal.jpg'      where slug='mega-deal';
update "Deal"     set image='deals/three-13-inch.jpg'      where slug='three-13-inch';
update "Deal"     set image='deals/three-20-inch.jpg'      where slug='three-20-inch';
update "Deal"     set image='deals/two-pizzas-medium.jpg'      where slug='two-pizzas-medium';
update "Category" set image='categories/cat-chicken.jpg' where slug='chicken';
update "Category" set image='categories/cat-desserts.jpg' where slug='desserts';
update "Category" set image='categories/cat-drinks.jpg' where slug='drinks';
update "Category" set image='categories/cat-pasta.jpg' where slug='pasta';
update "Category" set image='categories/cat-pizzas.jpg' where slug='pizzas';
update "Category" set image='categories/cat-sides.jpg' where slug='sides';
update "Category" set image='categories/cat-starters.jpg' where slug='starters';
